### PR TITLE
fix: aggregate text & functionCall(s) correctly

### LINKED ISSUE #494: Bug with function calling along with text streaming in generative AI with Gemini models
### Is this a client library issue or a product issue?
This is a client library issue.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

- **Programming language**: Node.js
- **OS**: macOS Sequoia
- **Language runtime version**: Node v22.12.0
- **Package version**: 1.9.3

#### Steps to reproduce

1. Wait until the AI decides to call a function along with text streaming. When this happens, the SDK appends the following incorrect format into the history (already verified that what I'm loading into the chat history is correct):
   ```json
   {
     "role": "model",
     "parts": [
       {
         "functionCall": {
           "name": "get_user_memory",
           "args": {}
         },
         "text": "undefined\n"
       }
     ]
   }
   ```
2. This leads to the following error:
   ```
   ClientError: [VertexAI.ClientError]: got status: 400 Bad Request. {"error":{"code":400,"message":"Invalid value at 'contents[15].parts[0]' (oneof), oneof field 'data' is already set. Cannot set 'text'","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"contents[15].parts[0]","description":"Invalid value at 'contents[15].parts[0]' (oneof), oneof field 'data' is already set. Cannot set 'text'"}]}]}}
   ```

3. The correct format should be:
   ```json
   {
     "role": "model",
     "parts": [
       {
         "functionCall": {
           "name": "get_user_memory",
           "args": {}
         }
       },
       { 
         "text": "undefined\n"
       }
     ]
   }
   ```

### Workaround
Inside `src/functions/generate_content` -> function `generateContentStream`, modify the request processing:

```js
if (request.contents && Array.isArray(request.contents)) {
    request.contents = request.contents.map(content => {
      if (content.parts && Array.isArray(content.parts)) {
        const newParts = [];
        content.parts.forEach(part => {
          // If both functionCall and text exist, split them to avoid the bug
          if (part.functionCall && part.text !== undefined) {
            if (Object.keys(part.functionCall).length > 0) {
              newParts.push({ functionCall: part.functionCall });
            }
            if (part.text && part.text.trim() !== '') {
              newParts.push({ text: part.text });
            }
          } else {
            newParts.push(part);
          }
        });
        content.parts = newParts;
      }
      return content;
    });
}
```

This workaround demonstrates where the failure occurs and ensures that the function call and text parts are properly separated, preventing the invalid `oneof` field error, though it does not fully resolve the underlying issue.

Thanks!

### PR DESCRIPTION
**Pull request by 6utt3rfly**
the content parts should have either `text` or `functionCall` set, but never both at once. When aggregating, combine the text (as before), but add `functionCall`(s) as new part(s). ~~Then when done, if the text from `part[0]` is empty, that part can be removed.~~ _(edit - I found that multiple responses were then resulting in the aggregate `undefined\n`, so now the empty text is always left as the first part)_

fixes #494

### CODE REVIEW

**Comment by yyyu-google** [comment]
thank you for contributing to the bug fix, unit test failed due to the style check, could you do `npm run fix`? see script in package.json https://github.com/googleapis/nodejs-vertexai/blob/46f655b9e6940f6e90bf7be25dfb7cd8910cd6dd/package.json#L21

File: src/functions/post_fetch_processing.ts [hunk 1]
```diff
@@ -273,6 +272,13 @@ export function aggregateResponses(
       }
     }
   }
+  if (aggregatedResponse.candidates?.length) {
+    aggregatedResponse.candidates.forEach((candidate) => {
+      if (candidate.content.parts.length > 1 && candidate.content.parts[0].text === '') {
+        candidate.content.parts.shift(); // remove empty text parameter
```
Comment (yyyu-google) [inline src/functions/post_fetch_processing.ts:278]: thank you for the PR! could you help me understand why do you only check the text field of the first element in the parts array?

Comment (6utt3rfly) [reply src/functions/post_fetch_processing.ts:281]: Ultimately, the aggregated response needs to avoid parts with both `text` and `functionCall` in the same part. It also needs to avoid an empty `text` string part if there is a `functionCall` part, but if there is no `functionCall`, then it needs that empty (or aggregated) `text` string.

On line 221, the aggregator creates a default, `parts: [{text: ''}]`. (index 0)

The old implementation would loop, delete the `text` property, and add the `functionCall` property to that one part. However, if there is another loop after that, line 254 would end up with `{undefined} += part.text`, which is invalid. It also needs to handle multiple responses and multiple possible `functionCall` parts, so I structured the code to always keep the aggregated text at part[0], while adding all `functionCall` parts to the end of the array. That way, after looping, if there is an empty `text` in the first index, it can be removed.

**Review by yyyu-google — APPROVED** [review]
